# Configure different targets, selectors (16-20) specify how to select them 
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: main
  namespace: monitoring
spec:
  version: v2.46.0
  serviceAccountName: prometheus
  podMonitorSelector:
    matchLabels:
      prometheus: main
  podMonitorNamespaceSelector:
    matchLabels: {}
  serviceMonitorSelector:
    matchLabels:
      prometheus: main
  serviceMonitorNamespaceSelector:
    matchLabels: {}
  replicas: 1
  logLevel: info
  logFormat: logfmt
  retention: 1d
  scrapeInterval: 5s
  securityContext:
    fsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
  # CSI Driver for Stateful 
  # EBS CSI Driver for EKS 
  # storage:
  #   volumeClaimTemplate:
  #     spec:
  #       resources:
  #         requests:
  #           storage: 20Gi